### ISSUE TITLE
Man Path on macOS

### ISSUE THREAD

**Issue by jaywilliams** [ibara/oksh#13]
By default, when you install oksh on macOS, it places the man page under `/usr/local/man/man1/`. 

This location isn't used by macOS and therefore doesn't resolve when you type `man oksh` in your terminal. Ideally, the output path on macOS would be `/usr/local/share/man/man1/`. As a side note, this is also the location where Homebrew symlinks all man documentation for their packages.

**Comment by ibara** [comment]
Line 73 of `GNUmakefile`.
Tweak it, make sure it works, send a pull request.

**Comment by ibara** [comment]
Fixed with #14
