### ISSUE TITLE
release

### ISSUE THREAD

**Issue by hdatma** [ibara/oksh#19]
Please do not distribute a secure shell from an insecure website. What refrains you from distributing http://devio.us/~bcallah/oksh/oksh-20180502.tar.gz using github?

**Comment by ibara** [comment]
I run devio.us; I will only host tarballs on machines I have access to and trust.
You do not have to use oksh.

**Comment by hdatma** [comment]
You do not have to use github.

**Comment by hdatma** [comment]
The problem is not your trust of the website. The problem is its lack of a trusted https connection. We do not know whether we are downloading the original code or a malicious copy from a MITM.
