### ISSUE TITLE
Duplicate "Please add oksh to /etc/shells" from Makefile

### ISSUE THREAD

**Issue by larryhynes** [ibara/oksh#22]
Hi

make (on my machine, MacOS, GNU Make 3.8.1) automatically echoes the lines under `install:` in the Makefile, which means that the line about adding `oksh` to `/etc/shells` is printed twice:

```
[master] ~/src/oksh $ make install
install -d /Users/larry/local/bin
install -d /Users/larry/local/share/man/man1
install -c -s -m 755 oksh /Users/larry/local/bin
install -c -m 644 oksh.1 /Users/larry/local/share/man/man1/oksh.1
echo "Please add /Users/larry/local/bin/oksh to /etc/shells"
Please add /Users/larry/local/bin/oksh to /etc/shells
```

According to the [GNU make documentation](https://www.gnu.org/software/make/manual/html_node/Echoing.html), prefacing the `echo ...` with `@` will suppress the double output, which it does:

```
[master] ~/src/oksh $ make install
install -d /Users/larry/local/bin
install -d /Users/larry/local/share/man/man1
install -c -s -m 755 oksh /Users/larry/local/bin
install -c -m 644 oksh.1 /Users/larry/local/share/man/man1/oksh.1
Please add /Users/larry/local/bin/oksh to /etc/shells
```

There may be other ways around this, and you might be trying to cover portability bases that make this "fix" unworkable. It's not A Big Deal, but I thought it was worth mentioning.

**Comment by ibara** [comment]
Also true for POSIX make: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html
So sure.

**Comment by larryhynes** [comment]
Great. See #23
