### ISSUE TITLE
Does oksh support cross compilation?

### ISSUE THREAD

**Issue by firasuke** [ibara/oksh#45]
I'm attempting to cross compile oksh to a x86-64 architecture targeting musl libc (`CC=x86_64-linux-musl-gcc`), and I'm receiving the following error:

```C
checking for C compiler... ./configure: line 43: ./conftest: No such file or directory
could not build working executables
Please ensure your C compiler is a native compiler
```

Does `oksh` support cross compilation at all?

**Comment by ibara** [comment]
The configure script doesn't (I've been meaning to deal with that...) but you could do something like this to cross compile:
1. Run `./configure` as normal.
2. Edit `pconfig.h` and/or `Makefile` to suit your needs.
3. Run `make CC=x86_64-linux-musl-gcc`

That should create a cross compiled oksh.
In the future, I'd like to convert to autotools, but that's not super high on my todo list right now.

**Comment by firasuke** [comment]
Ok, thanks!

**Comment by firasuke** [comment]
So apparently, and in the case of cross compilation, I should pass `CC=gcc` with `gcc` being the host's C compiler, then modify the generated `Makefile` and change `CC` accordingly.

**Comment by ibara** [comment]
Correct. See step 3 :)

**Comment by ibara** [comment]
Again, autotools coming... eventually.

**Comment by firasuke** [comment]
Cool.

Waiting for it :)

**Comment by firasuke** [comment]
Ok, I've attempted a `./configure && make CC=$XTARGET-gcc` without modifying `pconfig.h` and I've encountered:

```C
x86_64-glaucus-linux-musl-gcc -pipe -O2 -DEMACS -DVI -w -D_GNU_SOURCE   -c -o edit.o edit.c
In file included from portable.h:39,
                 from config.h:28,
                 from edit.c:8:
pconfig.h:7:22: error: expected identifier or '(' before numeric constant
    7 | #define issetugid(x) 0
      |                      ^
make[1]: *** [<builtin>: edit.o] Error 1
```

Also, what macros require changing in `pconfig.h` when cross compiling to different architectures (say `powerpc64` and `aarch64`), or is it ok to leave `pconfig.h` unchanged if I want to ensure an identical setup of `oksh` for my target architectures as I'm providing the entire target environment as well?

**Comment by ibara** [comment]
Hmm... can you give more details about this error? That's a valid use of the preprocessor, so something else must be causing the problem.

As for different architectures, you should be able to cross compile for different CPUs without any changes.

**Comment by firasuke** [comment]
Yes, well I have a working x86-64 cross compilation toolchain that targets musl libc, and since I can't run `CC=$XTARGET-gcc ./configure` using the cross compiler from my toolchain, I resort to running just `./configure` to let oksh configure with the host's compiler `gcc` instead of my `$XTARGET-gcc` (which is `x86_64-glaucus-linux-musl-gcc`), then I attempt a build (without modifying the contents of `pconfig.h`) using my cross compiler `$XTARGET-gcc` by running `make CC=$XTARGET-gcc` and it throws the error shown above.

**Comment by ibara** [comment]
Hi. I've just implemented easy cross compilation for oksh.
Can you try grabbing the latest code and trying to cross compile? It should be as easy as
```
$ CC=$XTARGET-gcc CFLAGS="cflags you need" LDFLAGS="ldflags you need" ./configure --no-thanks
```

**Comment by firasuke** [comment]
Thanks for your work.

After some fiddling it appears to be working fine now (I had some issues with `signame`, `siglist`, `vis` and `reallocarray`, which is understandable based on the arch I'm planning to cross compile `oksh` to).

Also, good job on adding the `--enable-lto` flag. It's good to know that compiling `oksh` with LTO enabled is officially supported.

I think that does it for this issue. In the case of any issues related to cross compilation, I'll make sure to open a new issue (perhaps create a `cross compilation` tag for these types of issues).

**Comment by ibara** [comment]
Sounds good.

**Comment by ibara** [comment]
Also, if it's a particularly unusual platform, please share patches!

**Comment by firasuke** [comment]
Will do.

**Comment by firasuke** [comment]
Ok, I've done much testing and here are my findings.

The goal is to cross compile oksh from an x86-64 glibc based Linux system to an x86-64 musl based Linux system.

1. First case:
* with `--enable-lto`
* with `--no-thanks`
* with `CC=x86_64-glaucus-linux-musl-gcc` for configure & make
* without modifiying `pconfig.h`:

```C
/* This file automatically generated by configure.  */

#ifndef __dead
#define __dead __attribute__((__noreturn__))
#endif

/* #define __attribute__(x) */

/* #define HAVE_ASPRINTF */
/* #define HAVE_CONFSTR */
#define NO_CURSES
/* #define HAVE_PLEDGE */
/* #define HAVE_REALLOCARRAY */
/* #define HAVE_SETRESGID */
/* #define HAVE_SETRESUID */
/* #define HAVE_SIG_T */
/* #define HAVE_SRAND_DETERMINISTIC */
/* #define HAVE_ST_MTIM */
#define HAVE_ST_MTIMESPEC
/* #define HAVE_STRAVIS */
/* #define HAVE_STRLCAT */
/* #define HAVE_STRLCPY */
/* #define HAVE_STRTONUM */
/* #define HAVE_STRUNVIS */
/* #define HAVE_SIGLIST */
/* #define HAVE_SIGNAME */
/* #define HAVE_TIMERADD */
/* #define HAVE_TIMERSUB */
```

The resulting error is:
```C
x86_64-glaucus-linux-musl-gcc -pipe -fopenmp -g0 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -fira-loop-pressure -fipa-pta -fgraphite-identity -floop-nest-optimize -fmerge-all-constants -fdevirtualize-at-ltrans -fno-semantic-interposition -fvariable-expansion-in-unroller -flto -ftracer -funroll-loops -s -fno-plt -march=x86-64 -mtune=generic -mabi=sysv -mtls-dialect=gnu2 -mfpmath=both -malign-data=cacheline -DVI -w -D_GNU_SOURCE -std=gnu99   -c -o c_test.o c_test.c
c_test.c: In function 'test_eval':
c_test.c:339:10: error: 'struct stat' has no member named 'st_mtimespec'
  339 |        b1.st_mtime > b2.st_mtime) || s2 < 0);
      |          ^
c_test.c:339:24: error: 'struct stat' has no member named 'st_mtimespec'
  339 |        b1.st_mtime > b2.st_mtime) || s2 < 0);
      |                        ^
c_test.c:349:10: error: 'struct stat' has no member named 'st_mtimespec'
  349 |        b1.st_mtime < b2.st_mtime) || s1 < 0);
      |          ^
c_test.c:349:24: error: 'struct stat' has no member named 'st_mtimespec'
  349 |        b1.st_mtime < b2.st_mtime) || s1 < 0);
      |                        ^
make: *** [<builtin>: c_test.o] Error 1
```

2. Second case:
* with `--enable-lto`
* with `--no-thanks`
* with `CC=x86_64-glaucus-linux-musl-gcc` for configure & make
* with a modified `pconfig.h` (replacing the not modified `pconfig.h` with one generated from `CC=gcc` for configure):

```C
/* This file automatically generated by configure.  */

#define __dead __attribute__((__noreturn__))
#define HAVE_ASPRINTF
#define HAVE_CONFSTR
#define HAVE_NCURSES
#define issetugid(x) 0
#define HAVE_REALLOCARRAY
#define HAVE_SETRESGID
#define HAVE_SETRESUID
#define HAVE_SIG_T
#define HAVE_ST_MTIM
#define HAVE_SIGLIST
#define HAVE_TIMERADD
#define HAVE_TIMERSUB
```

The resulting error is:
```C
x86_64-glaucus-linux-musl-gcc -pipe -fopenmp -g0 -Ofast -fmodulo-sched -fmodulo-sched-allow-regmoves -fgcse-sm -fgcse-las -fira-loop-pressure -fipa-pta -fgraphite-identity -floop-nest-optimize -fmerge-all-constants -fdevirtualize-at-ltrans -fno-semantic-interposition -fvariable-expansion-in-unroller -flto -ftracer -funroll-loops -s -fno-plt -march=x86-64 -mtune=generic -mabi=sysv -mtls-dialect=gnu2 -mfpmath=both -malign-data=cacheline -DVI -w -D_GNU_SOURCE -std=gnu99   -c -o edit.o edit.c
In file included from portable.h:39,
                 from config.h:28,
                 from edit.c:8:
pconfig.h:7:22: error: expected identifier or '(' before numeric constant
    7 | #define issetugid(x) 0
      |                      ^
make: *** [<builtin>: edit.o] Error 1
```

3. Third case:
* with `--enable-lto`
* without `--no-thanks`
* with `CC=x86_64-glaucus-linux-musl-gcc` for configure & make
* there isn't a `pconfig.h`

The resulting error is:
```C
checking for C compiler... ./configure: line 128: ./conftest: No such file or directory
could not build working executables
Please ensure your C compiler is a native compiler
```

**Comment by ibara** [comment]
Some of this is expected. Some of it is not.

For scenario 1, you have to switch HAVE_ST_MTIMESPEC for HAVE_ST_MTIM. Maybe that should be the default, since that aligns with POSIX.

In scenario 2, musl has an issetugid function: https://git.musl-libc.org/cgit/musl/tree/include/unistd.h#n177
but perhaps glibc does not. Remove that line and things should be OK.

For scenario 3, it seems like your compiler failed to compile the C file into an object fie? Would need more info to figure out why.

**Comment by firasuke** [comment]
Ok, disregarding scenarios 2 and 3 since scenario 1 is what we'd expect from a cross-compilation effort, I've enabled `HAVE_ST_MTIM` and it went smooth without errors.

Ok, so now I'm trying to find what I need to enable for a basicc x86-64 musl based system (supposed to run on the everyday desktop machine for now). I definitely have a curses implementation so `#define HAVE_NCURSES` should definitely work.

Any other options I should enable in pconfig.h, or should I go for the ones enabled by my x86-64 glibc based host, and figure out what works and what no for musl?

Thanks again.

**Comment by ibara** [comment]
You would need to add the appropriate "-I/path/to/ncurses/headers" in CFLAGS and "-L/path/to/libncurses -lncurses" to LDFLAGS.

**Comment by firasuke** [comment]
For my use case, using the following `pconfig.h`:

```C
/* This file automatically generated by configure.  */

#ifndef __dead
#define __dead __attribute__((__noreturn__))
#endif

/* #define __attribute__(x) */

/* #define HAVE_ASPRINTF */
/* #define HAVE_CONFSTR */
#define HAVE_CURSES
/* #define HAVE_PLEDGE */
/* #define HAVE_REALLOCARRAY */
/* #define HAVE_SETRESGID */
/* #define HAVE_SETRESUID */
/* #define HAVE_SIG_T */
/* #define HAVE_SRAND_DETERMINISTIC */
#define HAVE_ST_MTIM
#define HAVE_ST_MTIMESPEC
/* #define HAVE_STRAVIS */
/* #define HAVE_STRLCAT */
/* #define HAVE_STRLCPY */
/* #define HAVE_STRTONUM */
/* #define HAVE_STRUNVIS */
/* #define HAVE_SIGLIST */
/* #define HAVE_SIGNAME */
/* #define HAVE_TIMERADD */
/* #define HAVE_TIMERSUB */
```

and adding `-lterminfo` solely to the generated `Makefile` (both with and without `-lcurses` work) (although using:
```Makefile
...
${PROG}: ${OBJS}
        ${CC} ${LDFLAGS} -o ${PROG} ${OBJS} -lterminfo
...
```

produces the intended executable.

I have some questions though:
1- I feel that I have to enable some more stuff in `pconfig.h`, should I manually go through each check if my future target system will support it or not, or leave it there (as shown above)?

2- Do I need both `HAVE_ST_MTIM` and `HAVE_ST_MTIMESPEC` enabled, or is it ok to only enable `HAVE_ST_MTIM` (as it produces the exact same executable?

3- Is it ok if I patched the Makefile after configuration to add `-lterminfo`, or is there a better way to do it?

**Comment by firasuke** [comment]
So after some more testing (and for an x86-64 musl target architecture):

1- `musl` doesn't have `__dead` and `__dead2` so `#define __attribute__(x)` is used.
2- `musl` has `asprintf` so `#define HAVE_ASPRINTF` is used.
3- `musl` has `confstr` so `#define HAVE_CONFSTR` is used.

4- I've provided `netbsd_curses` in the target environment so `HAVE_CURSES` is used.

5- `musl` has `issetugid` so `#define issetugid(x) 0` is used.
6- `musl` doesn't have `pledge` so `HAVE_PLEDGE` is removed.
7- `musl` doesn't have `reallocarray` so `HAVE_REALLOCARRAY` is removed.
8- `musl` has `setresgid` so `HAVE_SETRESGID` is used.
9- `musl` has `setresuid` so `HAVE_SETRESUID` is used.
10- `musl` has `sig_t` so `HAVE_SIG_T` is used.
11- `musl` has `st_mtim.tv_spec` so `HAVE_ST_MTIM` is used.

12- `musl` has `st_mtime` but not `st_mtimespec` so add or remove `HAVE_ST_MTIMESPEC`?

13- `musl` doesn't have `srand_deterministic` so `HAVE_SRAND_DETERMINISTIC` is removed.
14- `musl` doesn't have `stravis` so `HAVE_STRAVIS` is removed.
15- `musl` has `strlcat` so `HAVE_STRLCAT` is used.
16- `musl` has `strlcpy` so `HAVE_STRLCPY` is used.
17- `musl doesn't have `strotonum` so `HAVE_STRTONUM` is removed.
18- `musl` doesn't have `strunvis` so `HAVE_STRUNVIS` is removed.
19- `musl` doesn't have `sys_siglist` so `HAVE_SIGLIST` is removed.
20- `musl` doesn't have `sys_signame` so `HAVE_SIGNAME` is removed.
21- `musl` has `timeradd` so `HAVE_TIMERADD` is used.
22- `musl` has `timersub` so `HAVE_TIMERSUB` is used.

The resulting `pconfig.h`:
```C
#ifndef __dead
#define __dead __attribute__((__noreturn__))
#endif

#define __attribute__(x)

#define HAVE_ASPRINTF
#define HAVE_CONFSTR
#define HAVE_CURSES
#define issetugid(x) 0
#define HAVE_SETRESGID
#define HAVE_SETRESUID
#define HAVE_SIG_T
#define HAVE_ST_MTIM
#define HAVE_ST_MTIMESPEC
#define HAVE_STRLCAT
#define HAVE_STRLCPY
#define HAVE_TIMERADD
#define HAVE_TIMERSUB
```

The only question left is whether to add or remove `HAVE_ST_MTIMESPEC`, since `musl` has `st_mtime` but not `st_mtimespec`.

**Comment by ibara** [comment]
So the --no-thanks flag essentially means "I will take the responsibility of figuring out what I do and don't have on my system, but let's start by assuming I have nothing and we'll use oksh's built-in compatibility code." Now, all of oksh's compat code should work, but I definitely understand preferring the system's code.

You only need one of HAVE_ST_MTIM or HAVE_ST_MTIMESPEC. The HAVE_ST_MTIM define means your struct stat has the POSIX timekeeping, whereas the HAVE_ST_MTIMESPEC means you have the older pre-POSIX timekeeping.

Yes you will need to manually add -lterminfo after configuration. You could alternatively run configure as "LDFLAGS='-lterminfo' ./configure ..." and it will get added to the Makefile for you.

**Comment by firasuke** [comment]
Ok, thanks for your time and effort.

Here's the final (known to work) `pconfig.h` for anyone who's interested in porting `oksh` to an x86-64 musl based linux distribution:

```C
#define __dead __attribute__((__noreturn__))
#define HAVE_ASPRINTF
#define HAVE_CONFSTR
#define HAVE_CURSES
#define HAVE_SETRESGID
#define HAVE_SETRESUID
#define HAVE_SIG_T
#define HAVE_ST_MTIM
#define HAVE_STRLCAT
#define HAVE_STRLCPY
#define HAVE_TIMERADD
#define HAVE_TIMERSUB
```

**Comment by firasuke** [comment]
Apparently specifying `LDFLAGS=-lterminfo` (even with `-Lpath/to/libcurses`) will error out with:

```C
/home/firasuke/glaucus/toolchain/bin/../lib/gcc/x86_64-glaucus-linux-musl/10.2.0/../../../../x86_64-glaucus-linux-musl/bin/ld: /tmp/oksh.PHVNir.ltrans1.ltrans.o: in function `x_redraw.lto_priv.0':
<artificial>:(.text+0x1dd3): undefined reference to `cur_term'
/home/firasuke/glaucus/toolchain/bin/../lib/gcc/x86_64-glaucus-linux-musl/10.2.0/../../../../x86_64-glaucus-linux-musl/bin/ld: <artificial>:(.text+0x1df8): undefined reference to `tputs'
/home/firasuke/glaucus/toolchain/bin/../lib/gcc/x86_64-glaucus-linux-musl/10.2.0/../../../../x86_64-glaucus-linux-musl/bin/ld: /tmp/oksh.PHVNir.ltrans5.ltrans.o: in function `setspec.lto_priv.0':
<artificial>:(.text+0x2e48): undefined reference to `setupterm'
/home/firasuke/glaucus/toolchain/bin/../lib/gcc/x86_64-glaucus-linux-musl/10.2.0/../../../../x86_64-glaucus-linux-musl/bin/ld: <artificial>:(.text+0x3768): undefined reference to `cur_term'
/home/firasuke/glaucus/toolchain/bin/../lib/gcc/x86_64-glaucus-linux-musl/10.2.0/../../../../x86_64-glaucus-linux-musl/bin/ld: <artificial>:(.text+0x376e): undefined reference to `del_curterm'
collect2: error: ld returned 1 exit status
make: *** [Makefile:21: oksh] Error 1
```

which means it can't find `-lterminfo` anywhere (this might happen in some cross compiling toolchains that either have misconfigured search paths for `$TARGET-ld` (or different ones based on the target arch that might not be used on the host at all).

Funnily enough, manually editing the Makefile (or by using `sed`) and appending `-lterminfo` works without any errors (even after inspecting the final executable, the paths are all correct, which means it found `libterminfo`):
```Makefile
...
${PROG}: ${OBJS}
        ${CC} ${LDFLAGS} -o ${PROG} ${OBJS} -lterminfo
...
```

**Comment by ibara** [comment]
That might be a linker thing, requring strict ordering. Note the difference of location between LDFLAGS and where you put -lterminfo manually.

**Comment by firasuke** [comment]
Yes, I'm putting `-lterminfo` as the final value in my LDFLAGS, and yet it's still failing. It only works if I put it after ${OBJS} though.

**Comment by ibara** [comment]
That definitely sounds like the linker being strict. I can add a LIBS environment variable that will stick you -lterminfo after ${OBJS}.

If you don't see it soon, remind me.

**Comment by firasuke** [comment]
I appreciate all the effort you're putting into this.

Yes please do, it will be so much better than the ugliness I'm using just to append a single word:
```Shell
sed '/${PROG}: ${OBJS}/!b;n;s/$/ -lterminfo/' -i Makefile
```

**Comment by firasuke** [comment]
> That definitely sounds like the linker being strict. I can add a LIBS environment variable that will stick you -lterminfo after ${OBJS}.
> 
> If you don't see it soon, remind me.

^ Just reminding you, thanks.

**Comment by ibara** [comment]
Done.

**Comment by firasuke** [comment]
Thanks!
