### ISSUE TITLE
Is it possible to release a new tarball?

### ISSUE THREAD

**Issue by firasuke** [ibara/oksh#46]
Hey there, and thanks for your hard work.

After the changes that you've made (enabling cross compilation for oksh), would it be possible for you to release a new tarball for 6.7?

**Comment by ibara** [comment]
I definitely don't want to replace the current 6.7 tarball, since that would ruin the current packages.
I could release a version 6.7.1.

**Comment by firasuke** [comment]
Oh seems like a little misunderstanding happened here. My intention wasn't to replace the current 6.7 tarball, but release a new one as in 6.7.1 which is what I'm asking for.

Yes, please proceed to release a tarball version 6.7.1.

Thanks again.

**Comment by ibara** [comment]
I made a pre-release in the releases tab called oksh-6.7.1.

**Comment by firasuke** [comment]
Thanks, will be testing it shortly.
