### ISSUE TITLE
Provide sample ksh.kshrc

### ISSUE THREAD

**Issue by Ottaviocr** [ibara/oksh#52]
Hi,

I wonder if it is a good idea to provide a sample ksh.kshrc to be sourced from ~/.kshrc, as per native OpenBSD file, for example here:
http://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/etc/ksh.kshrc?rev=1.32

This could be useful for !OpenBSD installations and could be put in $prefix/usr/share/examples.

**Comment by ibara** [comment]
I think it's probably worthwhile to ship with this. We already ship with a default .profile (currently named profile but I'll rename soon to dot.profile).

I'm less certain about default installing it. I think I'd rather leave that up to the individual package maintainers (we can always put a note in README.md about it).
