### ISSUE TITLE
^L in vi mode prints the prompt incorrecty when PS1 is more than one line

### ISSUE THREAD

**Issue by gotroyb127** [ibara/oksh#54]
Hi and many thanks for your work regarding this port.

I recently updated from 6.7.1 to current `master` and I can see that in `vi` editing mode
now `Ctrl+l` clears the screen and prints the prompt (almost).

The issue that occured to me is that I am using a multiline `PS1` and that `Ctrl+l` only
redraws the last line of that.

The prompt as it is normally:
````
[5:34:32] 1 ~
>
````
After hitting `^L`:
````
> 
````

What I don't know is if this is a bug or if it is supposed to behave like that.

This patch seems to make it work as I expected:
````diff
diff --git a/vi.c b/vi.c
index d8e9722..1680cae 100644
--- a/vi.c
+++ b/vi.c
@@ -59,7 +59,7 @@ static int	Endword(int);
 static int	grabhist(int, int);
 static int	grabsearch(int, int, int, char *);
 static void	do_clear_screen(void);
-static void	redraw_line(int);
+static void	redraw_line(int, int);
 static void	refresh_line(int);
 static int	outofwin(void);
 static void	rewindow(void);
@@ -723,7 +723,7 @@ vi_cmd(int argcnt, const char *cmd)
 			break;
 
 		case CTRL('r'):
-			redraw_line(1);
+			redraw_line(1, 0);
 			break;
 
 		case '@':
@@ -1741,18 +1741,18 @@ do_clear_screen(void)
 			neednl = 0;
 	}
 #endif
-	redraw_line(neednl);
+	redraw_line(neednl, 1);
 }
 
 static void
-redraw_line(int neednl)
+redraw_line(int neednl, int full)
 {
 	(void) memset(wbuf[win], ' ', wbuf_len);
 	if (neednl) {
 		x_putc('\r');
 		x_putc('\n');
 	}
-	vi_pprompt(0);
+	vi_pprompt(full);
 	cur_col = pwidth;
 	morec = ' ';
 }
@@ -2113,7 +2113,7 @@ complete_word(int command, int count)
 			vi_error();
 			x_print_expansions(nwords, words, is_command);
 			x_free_words(nwords, words);
-			redraw_line(0);
+			redraw_line(0, 0);
 			return -1;
 		}
 		/*
@@ -2187,7 +2187,7 @@ print_expansions(struct edstate *e)
 	}
 	x_print_expansions(nwords, words, is_command);
 	x_free_words(nwords, words);
-	redraw_line(0);
+	redraw_line(0, 0);
 	return 0;
 }
 
````
I could submit a Pull Request if that could help.

**Comment by ibara** [comment]
This would be an issue to bring up with the OpenBSD tech@ mailing list.
I intentionally don't forward carry patches; oksh always matches OpenBSD ksh behavior (good and bad).
Please test your setup on an OpenBSD machine and if it's not right, send a patch and then I'll sync oksh.

**Comment by gotroyb127** [comment]
Well, that's fair enough.

Though due to my lack of experience with that kind of things, I find myself uncapable of doing so.

I managed to get a OpenBSD running in a VM with qemu and I can confirm that the issue appears
when `PS1` contains a newline (`\n`). I got a bit stuck at getting the source code and compiling etc...

Anyway, I will not continue further submitting at their mailing list. It easy enough for me to patch this version every time there is a need. And I am happy enough for that.

So, if anyone is willing, he/she could use the small patch posted above.

It seems to me that you can close this issue if you think this is appropriate.

Thank you for your time and effort!

**Comment by ibara** [comment]
That's a bit disappointing. Why not benefit everyone?
You don't have to build oksh on the OpenBSD machine. The default shell is oksh. That's the point of this repository.
You said you were able to replicate it on your OpenBSD VM, so what not email your patch to them?

**Comment by gotroyb127** [comment]
Ok. Thanks to your message, I made a second try and sent an email at tech@. I think this is the most I can do for now.

**Comment by ibara** [comment]
That was a great mail to tech@. I'm glad to have been given the nudge.
I'll sync oksh when any changes happen.

**Comment by ibara** [comment]
Your fixes were committed to OpenBSD. I've merged them into here.
Thanks again for the bug report, and double thanks for reporting it to tech@!

**Comment by netzbasis** [comment]
Congrats on a successful bug report.

And quick update of this repo.
