### ISSUE TITLE
Announcement: renaming branch to main on 11/26.

### ISSUE THREAD

**Issue by ibara** [ibara/oksh#56]
Hello all --

This is a note that we will be changing the branch name to main on November 26, 2020. This is about one week's time for people to prepare if needed.

**Comment by ibara** [comment]
On hold since I discovered that GitHub is going to make it easy for us soon: https://github.com/github/renaming#later-this-year

**Comment by ibara** [comment]
We're now using main as the branch name. (oksh only has 1 branch)

**Comment by keithbowes** [comment]
It really messes me up when people use "main" instead of the standard "master", but I suppose the PC police had a problem with "master".
