### ISSUE TITLE
FreeBSD 12.2p4:  ^L in vi-mode prints as a string of literals rather than clearing the screen

### ISSUE THREAD

**Issue by jeanpierredevilliers** [ibara/oksh#59]
The title pretty much sums it up.  All I can really add is that on OpenBSD ^L behave as intended in both emacs and vi modes.  On the other hand, on FreeBSD ^L behaves as described in the documentation exclusively when in emacs mode.  

The FreeBSD host in question is a remote host accessed via SSH.

**Comment by ibara** [comment]
I will need to look into this.

**Comment by ibara** [comment]
I can confirm this, but I'll have to do some more digging a bit later.

**Comment by ibara** [comment]
Discovered the issue. If you change line 25 to
`#undef CTRL`
and remove line 27, then ^L works in vi mode on FreeBSD.
