### ISSUE TITLE
$RANDOM within scripts returns the same value

### ISSUE THREAD

**Issue by stripedswan** [ibara/oksh#69]
running 'print $RANDOM' works as expected, but once it is put inside a script it returns the same value every time the script is run.

issue reproduced in 7.1 on FreeBSD 13.1 both from ports and when compiled with clang.

**Comment by jsarenik** [comment]
I am unable to reproduce this with freshly compiled `oksh` from `master` branch on OpenBSD 7.1 amd64.

The script I use:

```sh
print $RANDOM
print $RANDOM
print $RANDOM
print $RANDOM
print $RANDOM
```

Gives me five different random numbers on output.

Remember that setting `A=$RANDOM` and then doing five times `print $A` would give me the same number five times.

**Comment by ibara** [comment]
It works fine on OpenBSD but doesn't work fine on at least FreeBSD and Illumos.
A quick guess: perhaps the `srand` call is always using the same seed. But I'll need to do more investigating.

**Comment by stripedswan** [comment]
The issue is no longer reproducible in FreeBSD 13.2.
