### ISSUE TITLE
update to latest code in src

### ISSUE THREAD

**Issue by akacase** [ibara/oksh#7]
Leaving this here to merge changes from latest upstream into master. I'll prepare a commit with the updates unless anyone objects?

**Comment by qbit** [comment]
Make sure you check the `newtest` branch.. and maybe one or two others, they have some fixes for various things (can't remember what :D)

**Comment by ibara** [comment]
I've updated to the newest OpenBSD code (and added Cygwin support, yay!).
I guess I'm going to close this now.
