### ISSUE TITLE
ksh attempts to cd into non-existent cdpath before trying argument first

### ISSUE THREAD

**Issue by apprehensions** [ibara/oksh#73]
```
/tmp $ unset CDPATH
/tmp $ mkdir foo
/tmp $ cd foo
/tmp/foo $ CDPATH=/tmp
/tmp/foo $ mkdir bar
/tmp/foo $ cd bar
/bin/ksh: cd: bar: bad directory
/tmp/foo $ unset CDPATH
/tmp/foo $ cd bar
/tmp/foo/bar $
```

**Comment by ibara** [comment]
OK. Can you write up more about what is happening here and what you'd expect to happen?

**Comment by apprehensions** [comment]
i simply wanted to cd into a directory i had made that is outside of the CDPATH, i expected to cd into the directory that is in the cwd, but it failed since it simply attempted to look in the CDPATHs for a directory, since the given argument was not a literal absolute path (`./foo`), it fails; as it had no matching directory in the available CDPATHS with a `foo` directory.

**Comment by ibara** [comment]
Thanks. That's helpful.

**Comment by ibara** [comment]
I have not sent any emails yet. Feel free to send your email.

**Comment by apprehensions** [comment]
they ultimately decided it wasn't a bug.
> All a bit of a mess isn't it. ksh's behaviour does at least mean you're less likely to change to an unexpected directory.

aditionally, i got a solution to another problem i had.

> So setting CDPATH=:/tmp or CDPATH=.:/tmp will work as expected.

you can see the archive [here](https://marc.info/?t=167844873400002&r=1&w=2). i would like to see what you think about it.

**Comment by ibara** [comment]
> they ultimately decided it wasn't a bug.
> 
> > All a bit of a mess isn't it. ksh's behaviour does at least mean you're less likely to change to an unexpected directory.
> 
> aditionally, i got a solution to another problem i had.
> 
> > So setting CDPATH=:/tmp or CDPATH=.:/tmp will work as expected.
> 
> you can see the archive [here](https://marc.info/?t=167844873400002&r=1&w=2). i would like to see what you think about it.

I'm an OpenBSD developer myself, so yes I read the whole thread as it happened.
My feelings are the same as tb@'s, I'm indifferent as to whether or not the behavior gets changed. I will encourage you to write that manual page change you suggested in your latest email.

**Comment by apprehensions** [comment]
> I will encourage you to write that manual page change you suggested in your latest email.

No way! My wording is horrible and should NOT end up in ksh man pages, plus I don't know how I would even note it in the first place.

**Comment by ibara** [comment]
> > I will encourage you to write that manual page change you suggested in your latest email.
> 
> No way! My wording is horrible and should NOT end up in ksh man pages, plus I don't know how I would even note it in the first place.

No diff is ever ready the first time. Write it, submit it, be open to feedback, revise and refine. And it will get in.
