### ISSUE TITLE
releases lack NEWS

### ISSUE THREAD

**Issue by gdt** [ibara/oksh#78]
Users benefit from a brief description of user-visible changes in a release, such as API/ABI breaks, new features, etc.  I am referring to what the GNU coding standards expects in NEWS.   At least some packaging systems ask that this be included with update commits.   In considering an update to 2.8 for pkgsrc, I did not find NEWS or something that had NEWS-like contents, and the github release page didn't have it either.

**Comment by ibara** [comment]
I'll do `git status > NEWS` starting with oksh-7.7
