### ISSUE TITLE
Problem with signature on opensuse.org

### ISSUE THREAD

**Issue by samarulmeu** [ibara/oksh#82]
There is a problem with the signature on opensuse.org

```
pub   rsa2048 2016-04-15 [SC] [expired: 2024-12-09]
uid           [ expired] home:Head_on_a_Stick OBS Project <home:Head_on_a_Stick@build.opensuse.org>
```

I do not know if here should I report it.

**Comment by ibara** [comment]
I don't use opensuse.org so I'm not sure what this is telling you.
I just made the release of oksh-7.6, maybe that will work?

**Comment by samarulmeu** [comment]
There is the link on the README for Debian distros. This is what I am using for easier upgrade. I will try reporting somewhere else.
