### ISSUE TITLE
Support for set -euo pipefail?

### ISSUE THREAD

**Issue by mcandre** [ibara/oksh#9]
Which debugging flags to the `set` command does oksh support? Can administrators run `set -euo pipefail` in oksh scripts, in order to code defensively?

**Comment by akacase** [comment]
no, there is no pipefail option. I can suggest mksh if you're looking for ksh with more bashisms.

**Comment by ibara** [comment]
I'm going to close this, since it's a "can't fix" as I just follow upstream OpenBSD ksh code.
But thanks for your comment and interest!
